# Dotnet action setup
# https://github.com/actions/setup-dotnet
# https://docs.github.com/en/actions/guides/building-and-testing-net
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      working-directory: Common
      run: dotnet restore 
    - name: Build dotnet
      working-directory: Common
      run: dotnet build --no-restore
    - name: Test
      working-directory: test/Common
      run: dotnet test --no-build --verbosity normal